### PR TITLE
Set proxyauth to "any" when Faraday request includes proxy credentials.

### PR DESCRIPTION
**Pull request by scotje**
#463 would provide a framework for a more general solution to this, I can work on fixing up that PR instead if you think this is too inflexible.

### CODE REVIEW

**Comment by scotje** [comment]
Also, let me know if there is a test you would like to see added around this.

**Comment by scotje** [comment]
Spec test failure on rbx doesn't seem related? But I don't really have any experience with rbx...

**Comment by i0rek** [comment]
@scotje thank you very much for your work! I like your change.

**Comment by scotje** [comment]
Cool, thanks!

**Comment by scotje** [comment]
Is there a existing release cadence or any sort of process for requesting a release that would include this change? It's not urgent but sometime in the next couple weeks would be helpful. :)

**Comment by i0rek** [comment]
I released a new version.

**Comment by scotje** [comment]
Great! Thank you very much!

**Pull request merged**
