### PR TITLE
Closes #693 Allow performing `curl --upload-file`

### LINKED ISSUE #693: How to perform `curl --upload-file`
I want to use the `curl --upload-file` option described here:

https://curl.se/docs/manual.html#uploading

> HTTP
>
> Upload all data on stdin to a specified HTTP site:
>
> curl -T - http://www.upload.com/myfile
> Note that the HTTP server must have been configured to accept PUT before this can be done successfully.
>
> For other ways to do HTTP data upload, see the POST section below.

This is what works for me in curl: `curl -X POST -v “<UPLOAD_URL>" --upload-file <FILE_PATH>`

Is that the same as what is described here: https://github.com/typhoeus/typhoeus/blob/master/README.md#handling-file-uploads

```ruby
Typhoeus.post(
  "http://localhost:3000/posts",
  body: {
    file: File.open("thesis.txt","r")
  }
)
```

From inspecting the server request, they seem to be doing different things?

### PR DESCRIPTION
**Pull request by arianf**
Ethon supports setting up a `set_read_callback(body)` currently, which is not exposed to Typhoeus.

If you want to mimic `curl “<UPLOAD_URL>" --upload-file <FILE_PATH>` in Typhoeus this is currently not possible.

With this change you'll be allowed to invoke the curls `readfunction` with:

```ruby
Typhoeus.put("localhost:3000",
  set_read_callback: File.open('/Users/arian/tmp/TestFile.zip')
)
```

### CODE REVIEW

**Comment by arianf** [comment]
I don't think those tests are failing due to my code changes, how would I verify that?

**Comment by Kjarrigan** [comment]
Please rebase against master. I just adjusted the test-suite and dropped the (EOL) Ruby versions < 2.5

**Comment by arianf** [comment]
Okay, @Kjarrigan should be ready

**Comment by Kjarrigan** [comment]
Merged. Thanks for your contribution @arianf

**Pull request merged**
