### PR TITLE
Add cache adapters for Dalli, Rails, and Redis.

### PR DESCRIPTION
**Pull request by isaacseymour**
Re: #545 - rather than asking users to copy-paste the glue from the README, this provides the cache adapters for using Dalli, Rails.cache, and Redis, which should cover most cases I think? @i0rek what do you think?

### CODE REVIEW

**Comment by i0rek** [comment]
@isaacseymour this looks great! Looking at the code and the structure I was wondering if it would be worth it to put the caches into their own module and folder. Like `Typhoeus::Cache::Dalli` would live in `lib/typhoeus/cache/dalli.rb`. What do you think about that?

**Comment by isaacseymour** [comment]
I couldn't decide, but looking at it again I'd agree it should go into a
separate module. Will update in the morning. Thanks for the speedy
response! :)

**Comment by isaacseymour** [comment]
@i0rek Updated. CI is failing because:
- Dalli doesn't support Ruby < 1.9 (which is very discontinued, so maybe support can be removed from Typhoeus?)
- Rubinius seems to not be working on Travis at all

So not really sure what to do about those.

**Comment by i0rek** [comment]
@isaacseymour thank you! I would like to maintain ruby 1.8 compat as long as it is not a big deal. In this case I don't think the reasons are compelling enough. Can we not load the dalli adapter in ruby 1.8? Rbx tests don't work atm :(

**Comment by isaacseymour** [comment]
What's the reasoning for keeping 1.8 support? It was EOLed over 2 years ago now (by which point it was [<2% market share][0])! I'm happy to conditionally load the Dalli adapter only on 1.9+, but seems kinda crazy to keep supporting such an old Ruby version.

[0]:https://semaphoreci.com/blog/2014/08/27/ruby-version-usage-in-commercial-projects-2014-edition.html

**Comment by i0rek** [comment]
I don't want to screw ppl who are still using ruby 1.8. There are also very few things that cause problems with these old versions. Basically, this is just me trying to be nice :).

**Comment by isaacseymour** [comment]
I'd argue it's _not_ nice to allow people to use software that's not received security patches in several years, but can see the other argument. I'll make the Dalli-tests skip on Ruby 1.8 this evening.

**Comment by isaacseymour** [comment]
Alright, had to disable installing Faraday on 1.8 too (they've dropped support for <1.9), but all the tests except rbx-2 are passing 💪

**Comment by i0rek** [comment]
Thank you very much!

**Comment by chriso0710** [comment]
Yes, great job @isaacseymour !

**Pull request merged**
