### PR TITLE
Add on_progress callback

### PR DESCRIPTION
**Pull request by zachwalton**
This closes out issue https://github.com/typhoeus/typhoeus/issues/554.

The `on_progress` callback was [added to ethon](https://github.com/typhoeus/ethon/pull/139) but as far as I can tell [BackOrder's change](https://github.com/typhoeus/typhoeus/commit/1ed499a0c3f8a8859e386ba1d084ac03b8af23e5) was never added to typhoeus.

This adds the `on_progress` callback and some tests.

### CODE REVIEW

**Comment by zachwalton** [comment]
Hi there!

Any chances of this going in? We'd love to un-fork :)

**Comment by i0rek** [comment]
Sorry, missed your PR!

Could you add your callback https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/request/marshal.rb#L10 as well?

Looks great otherwise, will merge.

**Comment by zachwalton** [comment]
Thanks a lot @i0rek, no worries!

Done https://github.com/typhoeus/typhoeus/pull/600/commits/8c92f089f0652fda3517c1be809fcbf4fc22ac06

**Comment by i0rek** [comment]
Thanks for your work!

**Pull request merged**
