### PR TITLE
Readme help for Put and param sending gotcha

### PR DESCRIPTION
**Pull request by ryan2johnson9**
After I read issue #332 I wondered why the info was not in the README. Please check this as it may not be correctly worded, and indeed does it also need to be for Patch?

### CODE REVIEW

**Comment by i0rek** [comment]
Thanks for your work! I know what you mean and this is definitely a thing many run into. I would like to phrase a bit different though. I think it should be more along the way: "When using POST the content-type is set automatically to 'application/x-www-form-urlencoded'. Thats not the case for any other method like PUT, PATCH, HEAD and so on. No matter if you are using `body` or not." See the corresponding libcurl docs: http://curl.haxx.se/libcurl/c/CURLOPT_POST.html.

What do you think?

**Comment by ryan2johnson9** [comment]
@i0rek, thanks for that. But given what you've said and the link, I still would not have known how to fix my problem without that example I gave. Would it be okay to leave the example 'PUT' in there? I've updated my pull request given your feedback. Let me know if it is not correct.

**Comment by i0rek** [comment]
@ryan2johnson9 thank you very much for your work!

**Comment by ryan2johnson9** [comment]
You're welcome - I should be the one thanking you and all contributors for Typhoeus! Unfortunately there was a typo in this merged pull request so I've submitted another pull request to fix it, as well as adjusting the example's body params to be more clear.. see #433

**Pull request merged**
